/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * StreamGram API - Telegram channel video streaming
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthStatus,
  AuthVerifyResult,
  Category,
  CodeSendResult,
  HealthStatus,
  ListSeriesParams,
  PhoneSendInput,
  PhoneVerifyInput,
  Series,
  SyncResult
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAuthStatusUrl = () => {




  return `/api/auth/status`
}

/**
 * @summary Check whether the Telegram session is authenticated
 */
export const getAuthStatus = async ( options?: RequestInit): Promise<AuthStatus> => {

  return customFetch<AuthStatus>(getGetAuthStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthStatusQueryKey = () => {
    return [
    `/api/auth/status`
    ] as const;
    }


export const getGetAuthStatusQueryOptions = <TData = Awaited<ReturnType<typeof getAuthStatus>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthStatus>>> = ({ signal }) => getAuthStatus({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthStatus>>>
export type GetAuthStatusQueryError = ErrorType<unknown>


/**
 * @summary Check whether the Telegram session is authenticated
 */

export function useGetAuthStatus<TData = Awaited<ReturnType<typeof getAuthStatus>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getSendAuthCodeUrl = () => {




  return `/api/auth/send-code`
}

/**
 * @summary Send Telegram verification code to a phone number
 */
export const sendAuthCode = async (phoneSendInput: PhoneSendInput, options?: RequestInit): Promise<CodeSendResult> => {

  return customFetch<CodeSendResult>(getSendAuthCodeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      phoneSendInput,)
  }
);}




export const getSendAuthCodeMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendAuthCode>>, TError,{data: BodyType<PhoneSendInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof sendAuthCode>>, TError,{data: BodyType<PhoneSendInput>}, TContext> => {

const mutationKey = ['sendAuthCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendAuthCode>>, {data: BodyType<PhoneSendInput>}> = (props) => {
          const {data} = props ?? {};

          return  sendAuthCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendAuthCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendAuthCode>>>
    export type SendAuthCodeMutationBody = BodyType<PhoneSendInput>
    export type SendAuthCodeMutationError = ErrorType<void>

    /**
 * @summary Send Telegram verification code to a phone number
 */
export const useSendAuthCode = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendAuthCode>>, TError,{data: BodyType<PhoneSendInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof sendAuthCode>>,
        TError,
        {data: BodyType<PhoneSendInput>},
        TContext
      > => {
      return useMutation(getSendAuthCodeMutationOptions(options));
    }

export const getVerifyAuthCodeUrl = () => {




  return `/api/auth/verify-code`
}

/**
 * @summary Verify OTP code and establish a session
 */
export const verifyAuthCode = async (phoneVerifyInput: PhoneVerifyInput, options?: RequestInit): Promise<AuthVerifyResult> => {

  return customFetch<AuthVerifyResult>(getVerifyAuthCodeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      phoneVerifyInput,)
  }
);}




export const getVerifyAuthCodeMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyAuthCode>>, TError,{data: BodyType<PhoneVerifyInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyAuthCode>>, TError,{data: BodyType<PhoneVerifyInput>}, TContext> => {

const mutationKey = ['verifyAuthCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyAuthCode>>, {data: BodyType<PhoneVerifyInput>}> = (props) => {
          const {data} = props ?? {};

          return  verifyAuthCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VerifyAuthCodeMutationResult = NonNullable<Awaited<ReturnType<typeof verifyAuthCode>>>
    export type VerifyAuthCodeMutationBody = BodyType<PhoneVerifyInput>
    export type VerifyAuthCodeMutationError = ErrorType<void>

    /**
 * @summary Verify OTP code and establish a session
 */
export const useVerifyAuthCode = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyAuthCode>>, TError,{data: BodyType<PhoneVerifyInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof verifyAuthCode>>,
        TError,
        {data: BodyType<PhoneVerifyInput>},
        TContext
      > => {
      return useMutation(getVerifyAuthCodeMutationOptions(options));
    }

export const getListSeriesUrl = (params?: ListSeriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/series?${stringifiedParams}` : `/api/series`
}

/**
 * @summary List all series
 */
export const listSeries = async (params?: ListSeriesParams, options?: RequestInit): Promise<Series[]> => {

  return customFetch<Series[]>(getListSeriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSeriesQueryKey = (params?: ListSeriesParams,) => {
    return [
    `/api/series`, ...(params ? [params] : [])
    ] as const;
    }


export const getListSeriesQueryOptions = <TData = Awaited<ReturnType<typeof listSeries>>, TError = ErrorType<unknown>>(params?: ListSeriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSeries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSeriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSeries>>> = ({ signal }) => listSeries(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSeries>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSeriesQueryResult = NonNullable<Awaited<ReturnType<typeof listSeries>>>
export type ListSeriesQueryError = ErrorType<unknown>


/**
 * @summary List all series
 */

export function useListSeries<TData = Awaited<ReturnType<typeof listSeries>>, TError = ErrorType<unknown>>(
 params?: ListSeriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSeries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListSeriesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetFeaturedSeriesUrl = () => {




  return `/api/series/featured`
}

/**
 * @summary Get featured series for hero banner
 */
export const getFeaturedSeries = async ( options?: RequestInit): Promise<Series> => {

  return customFetch<Series>(getGetFeaturedSeriesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFeaturedSeriesQueryKey = () => {
    return [
    `/api/series/featured`
    ] as const;
    }


export const getGetFeaturedSeriesQueryOptions = <TData = Awaited<ReturnType<typeof getFeaturedSeries>>, TError = ErrorType<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFeaturedSeries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeaturedSeriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeaturedSeries>>> = ({ signal }) => getFeaturedSeries({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeaturedSeries>>, TError, TData> & { queryKey: QueryKey }
}

export type GetFeaturedSeriesQueryResult = NonNullable<Awaited<ReturnType<typeof getFeaturedSeries>>>
export type GetFeaturedSeriesQueryError = ErrorType<void>


/**
 * @summary Get featured series for hero banner
 */

export function useGetFeaturedSeries<TData = Awaited<ReturnType<typeof getFeaturedSeries>>, TError = ErrorType<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFeaturedSeries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetFeaturedSeriesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetRecentSeriesUrl = () => {




  return `/api/series/recent`
}

/**
 * @summary Get recently added series
 */
export const getRecentSeries = async ( options?: RequestInit): Promise<Series[]> => {

  return customFetch<Series[]>(getGetRecentSeriesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRecentSeriesQueryKey = () => {
    return [
    `/api/series/recent`
    ] as const;
    }


export const getGetRecentSeriesQueryOptions = <TData = Awaited<ReturnType<typeof getRecentSeries>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecentSeries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentSeriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentSeries>>> = ({ signal }) => getRecentSeries({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentSeries>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecentSeriesQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentSeries>>>
export type GetRecentSeriesQueryError = ErrorType<unknown>


/**
 * @summary Get recently added series
 */

export function useGetRecentSeries<TData = Awaited<ReturnType<typeof getRecentSeries>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecentSeries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecentSeriesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getSyncSavedMessagesUrl = () => {




  return `/api/series/sync`
}

/**
 * @summary Bulk-import video files from Telegram Saved Messages
 */
export const syncSavedMessages = async ( options?: RequestInit): Promise<SyncResult> => {

  return customFetch<SyncResult>(getSyncSavedMessagesUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getSyncSavedMessagesMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncSavedMessages>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof syncSavedMessages>>, TError,void, TContext> => {

const mutationKey = ['syncSavedMessages'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncSavedMessages>>, void> = () => {


          return  syncSavedMessages(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncSavedMessagesMutationResult = NonNullable<Awaited<ReturnType<typeof syncSavedMessages>>>

    export type SyncSavedMessagesMutationError = ErrorType<void>

    /**
 * @summary Bulk-import video files from Telegram Saved Messages
 */
export const useSyncSavedMessages = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncSavedMessages>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof syncSavedMessages>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncSavedMessagesMutationOptions(options));
    }

export const getGetSeriesByIdUrl = (id: number,) => {




  return `/api/series/${id}`
}

/**
 * @summary Get a single series by ID
 */
export const getSeriesById = async (id: number, options?: RequestInit): Promise<Series> => {

  return customFetch<Series>(getGetSeriesByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSeriesByIdQueryKey = (id: number,) => {
    return [
    `/api/series/${id}`
    ] as const;
    }


export const getGetSeriesByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSeriesById>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSeriesById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSeriesByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSeriesById>>> = ({ signal }) => getSeriesById(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSeriesById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSeriesByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSeriesById>>>
export type GetSeriesByIdQueryError = ErrorType<void>


/**
 * @summary Get a single series by ID
 */

export function useGetSeriesById<TData = Awaited<ReturnType<typeof getSeriesById>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSeriesById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSeriesByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListCategoriesUrl = () => {




  return `/api/categories`
}

/**
 * @summary List all categories with series count
 */
export const listCategories = async ( options?: RequestInit): Promise<Category[]> => {

  return customFetch<Category[]>(getListCategoriesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCategoriesQueryKey = () => {
    return [
    `/api/categories`
    ] as const;
    }


export const getListCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof listCategories>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCategories>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCategoriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCategories>>> = ({ signal }) => listCategories({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCategories>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listCategories>>>
export type ListCategoriesQueryError = ErrorType<unknown>


/**
 * @summary List all categories with series count
 */

export function useListCategories<TData = Awaited<ReturnType<typeof listCategories>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCategories>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCategoriesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







